version: '3.8'

services:
  crystal:
    build: ./src/crystal-lambda

  go:
    image: golang:1-alpine
    volumes:
      - ./src/go-lambda:/app
    working_dir: /app

  pkg:
    build:
      dockerfile: ./src/node-pkg-lambda/dockerfile.node
    volumes:
      - ./src/node-pkg-lambda:/app
